import { FormInputs } from "@/components/form";
import { type NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: NextRequest) {
  const {
    fullName,
    email,
    phoneNumber,
    businessName,
    projectDescription,
    budgetRange,
    projectTimeline,
    preferredContactMethod,
    tierName,
  }: FormInputs = await request.json();

  const transport = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.MY_EMAIL,
      pass: process.env.MY_PASSWORD,
    },
  });

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Courier New', Courier, monospace; background-color: #f0f0f0; padding: 20px; color: #111111; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border: 4px solid #111111; box-shadow: 12px 12px 0px 0px #111111; }
    .header { background: #BFFF00; border-bottom: 4px solid #111111; padding: 30px; }
    .header h1 { font-size: 32px; margin: 0; text-transform: uppercase; letter-spacing: -2px; line-height: 0.9; }
    .section { padding: 30px; border-bottom: 4px solid #111111; }
    .section-title { font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px; color: #666; margin-bottom: 20px; }
    .tier-badge { display: inline-block; background: #00E5FF; border: 2px solid #111111; padding: 5px 15px; font-weight: bold; margin-bottom: 10px; }
    .grid { display: block; width: 100%; }
    .row { border-bottom: 2px solid #eee; padding: 10px 0; }
    .label { font-weight: bold; text-transform: uppercase; font-size: 11px; color: #4320F6; }
    .value { font-size: 16px; margin-top: 4px; }
    .description { background: #fafafa; border: 2px solid #111111; padding: 20px; margin-top: 10px; line-height: 1.6; }
    .footer { padding: 20px; font-size: 10px; text-transform: uppercase; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="section-title">New Brief Received</div>
      <h1>Project<br>Inquiry.</h1>
    </div>

    <div class="section">
      <div class="section-title">Selected Package</div>
      <div class="tier-badge">${tierName}</div>
      <div class="value" style="font-weight: bold;">Est. ${budgetRange}</div>
    </div>

    <div class="section">
      <div class="section-title">Contact Profile</div>
      <div class="grid">
        <div class="row">
          <div class="label">Client</div>
          <div class="value">${fullName}</div>
        </div>
        <div class="row">
          <div class="label">Email / Phone</div>
          <div class="value">${email} ${phoneNumber ? `/ ${phoneNumber}` : ''}</div>
        </div>
        <div class="row">
          <div class="label">Business</div>
          <div class="value">${businessName || 'NOT SPECIFIED'}</div>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">The Vision</div>
      <div class="description">${projectDescription}</div>
    </div>

    <div class="section" style="border-bottom: none;">
      <div class="section-title">Operational Logic</div>
      <div class="grid">
        <div class="row">
          <div class="label">Target Timeline</div>
          <div class="value">${projectTimeline}</div>
        </div>
        <div class="row">
          <div class="label">Preferred Contact</div>
          <div class="value">${preferredContactMethod}</div>
        </div>
      </div>
    </div>

    <div class="footer">
      Generated by dpkreativ portfolio system // ${new Date().toISOString()}
    </div>
  </div>
</body>
</html>`;

  const mailOptions = {
    from: process.env.MY_EMAIL,
    to: process.env.MY_EMAIL,
    subject: `New project inquiry from ${fullName} (${email})`,
    html: htmlContent,
  };

  const sendMailPromise = () =>
    new Promise<string>((resolve, reject) => {
      transport.sendMail(mailOptions, function (err) {
        if (!err) {
          resolve("Email sent");
        } else {
          reject(err.message);
        }
      });
    });

  try {
    await sendMailPromise();
    return NextResponse.json({ message: "Email sent" });
  } catch (err) {
    return NextResponse.json({ error: `${err}` }, { status: 500 });
  }
}
