import Head from 'next/head';
import Image from 'next/image';
import { ArrowDown } from '../components/assets/Icons';
import HomeLayout from '../components/layouts/HomeLayout';
import Button from '../components/ui/atoms/Button';
import { Input, TextArea } from '../components/ui/atoms/Inputs';
import ProjectCard from '../components/ui/atoms/ProjectCard';
import Section from '../components/ui/organisms/Section';

export default function Home() {
  const year = new Date().getFullYear();

  return (
    <div>
      <Head>
        <title>Divine Orji - dpkreativ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dpkreativ.ico" />
      </Head>

      {/* Home Content */}
      <HomeLayout>
        {/* Hero Section */}
        <Section>
          <article className="flex justify-between items-end relative">
            <div className="text-5xl md:text-6xl lg:text-7xl leading-normal md:leading-normal lg:leading-normal md:w-4/5 font-semibold">
              Hi, I’m Divine — <span className="gray">a software engineer</span>{' '}
              who enjoys creating applications that are{' '}
              <span className="gray">fast</span>,{' '}
              <span className="gray">robust</span>, and{' '}
              <span className="gray">user-friendly</span>.
            </div>
            <div className="absolute right-0 bottom-24 animate-bounce">
              <ArrowDown />
            </div>
          </article>
        </Section>

        {/* Bio Section */}
        <Section title={`Bio`}>
          <article>
            <div className="font-semibold text-4xl gray mb-2">
              <span className="dance">circa </span>'97
            </div>
            <div className="relative w-full h-96 rounded-lg overflow-clip">
              <Image
                src={`/images/profile.jpg`}
                alt={`Divine Orji`}
                fill
                priority
                style={{ objectFit: 'cover' }}
              />
            </div>
          </article>
          <article className="text-2xl leading-normal grid gap-6 pt-6">
            <div>
              My dad owned a cybercafe and a printing business, so I had access
              to computers from childhood.
            </div>
            <div>
              I played around with Mavis Beacon, significantly improving my
              typing speed over the years, and with time I developed an interest
              in graphic design.
            </div>
          </article>
          <article className="text-2xl leading-normal grid gap-6 pt-6">
            <div>
              <span className="font-semibold">In 2019,</span> I enrolled in a
              tech bootcamp to learn frontend development, and since then I’ve
              worked on small and large applications, websites and APIs.
            </div>
            <div>
              I like to <span className="gray">think strategically</span> and
              solve problems in{' '}
              <span className="gray">small, iterative steps</span>, and I love{' '}
              <span className="gray">pairing up</span> with smart people to
              build great things.
            </div>
            <div>
              I also love <span className="gray">sharing knowledge</span> as
              part of a <span className="gray">community</span>, and I am an
              active member of multiple tech communities such as GDG Aba, GDSC
              MOUAU, and Polygon Guild Abuja.
            </div>
          </article>
        </Section>

        {/* Work Section */}
        <Section title={`Featured Projects`}>
          <article className="grid gap-8">
            <div className="text-8xl font-semibold mb-16">
              <span className="gray">2019 - </span>
              {year}
            </div>
            <ProjectCard title={`Wkkly`} topCategory={`productivity`} />
            <ProjectCard title={`Bicode`} topCategory={`collaboration`} />
            <ProjectCard title={`AfroChops`} topCategory={`ecommerce`} />
            <ProjectCard title={`Inaaga`} topCategory={`transportation`} />
          </article>
        </Section>

        {/* Contact Section */}
        <Section>
          <article>
            <div className="text-5xl font-semibold mb-6">
              Wanna collab <span className="gray">with me?</span>
            </div>
            <div>
              <div className="text-2xl flex relative w-80">
                <div>
                  <span className="dance gray">Please, </span>
                  <span className="font-semibold mr-48">send me a message</span>
                </div>
                <div className="absolute right-6 bottom-0 -mb-4">
                  <div className="relative w-48 h-16">
                    <Image
                      src={`/images/paper_plane.png`}
                      alt="a paper plane"
                      fill
                      style={{ objectFit: 'contain' }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </article>
          <article>
            <form className="mt-12 grid gap-5">
              <div className="grid gap-5">
                <Input
                  type={`text`}
                  id={`fullname`}
                  placeholder={`Your full name`}
                />
                <Input
                  type={`email`}
                  id={`emailAddress`}
                  placeholder={`Your email address`}
                />
              </div>
              <div>
                <TextArea id={`yourMessage`} placeholder={`Your message`} />
              </div>
              <div className="flex justify-end">
                <Button type={`submit`}>Send message</Button>
              </div>
            </form>
          </article>
        </Section>
      </HomeLayout>
    </div>
  );
}
