import Head from 'next/head';
import Image from 'next/image';
import { ArrowDown } from '../components/assets/Icons';
import HomeLayout from '../components/layouts/HomeLayout';
import HeroSection from '../components/ui/organisms/HeroSection';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home Content */}
      <HomeLayout>
        {/* Hero Section */}
        <HeroSection>
          <article className="flex justify-between items-end">
            <div className="text-7xl leading-normal font-semibold max-w-[80%]">
              Hi, I’m Divine — a software engineer who enjoys creating
              applications that are <span className="gray">fast</span>,{' '}
              <span className="gray">robust</span>, and{' '}
              <span className="gray">user-friendly</span>.
            </div>
            <div>
              <ArrowDown />
            </div>
          </article>
        </HeroSection>
      </HomeLayout>
    </div>
  );
}
