export const projects = [
  {
    id: 1,
    title: "Crunchies Online",
    client: "Crunchies Fried Chicken",
    description: "",
    url: "crunchiesonline.com",
    github: "",
    featured: true,
  },
  {
    id: 2,
    title: "IGHub Website",
    client: "Innovation Growth Hubs",
    description: "",
    url: "ighub.ng",
    github: "",
    featured: true,
  },
  {
    id: 3,
    title: "Sozonation",
    client: "Sozonation Org",
    description: "",
    url: "sozonation.org",
    github: "",
    featured: false,
  },
  {
    id: 4,
    title: "The Developer Marketing Book",
    client: "Decenta LLC",
    description: "",
    url: "devmarbook.com",
    github: "github.com/dpkreativ/devmarbook",
    featured: true,
  },
  {
    id: 5,
    title: "Phil's Auto Sales Website",
    client: "Phil's Auto Sales LLC",
    description: "",
    url: "philsautosalesllc.com",
    github: "",
    featured: false,
  },
];
